// Shared functions
#include <rock_the_upgrades/shared>

// Enable/Disable upgrade system, and easily reset entity upgrades
#include <rock_the_upgrades/upgrades_controller>

// Manages configurable currency gains and losses across various events
#include <rock_the_upgrades/currency_controller>

// Persistent, multi-target timer
#include <rock_the_upgrades/combat_timer>

// Allows upgrade menu access via bindable chat command
#include <rock_the_upgrades/pocket_upgrades>

// Enables voting and auto-enable of upgrade system
#include <rock_the_upgrades/voting>

// Allows defining custom upgrades via external file
#include <rock_the_upgrades/custom_upgrades>
